#!/bin/bash

export PATH="${PATH}:${HOME}/.local/bin/"

# Start swww daemon
if ! pgrep -x "swww-daemon" > /dev/null; then
    swww-daemon &
    sleep 1
fi

if [ -e "${HOME}/.cache/wal/colors" ]; then
    # Restore last wallpaper if it exists
    if [ -e "${HOME}/.cache/wal/wal" ]; then
        LAST_WALLPAPER=$(cat "${HOME}/.cache/wal/wal")
        swww img "${LAST_WALLPAPER}" --transition-type grow --transition-fps 60 --transition-duration 1.0 --transition-pos 0.810,0.972 --transition-bezier 0.65,0,0.35,1 --transition-step 255
    fi
    
    # Check mode and restore with correct flag
    if [[ -e "${HOME}/.cache/wal/mode" && "$(<~/.cache/wal/mode)" = "light" ]]; then
        wal -R -l --cols16
    else
        wal -R --cols16
    fi
    
    pywalfox update
    pywal-discord -t default

    echo "Cached colors exist. Using existing colors and wallpaper."
else
    DIR=$HOME/Wallpapers
    PICS=($(ls ${DIR}))

    RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}

    swww img ${DIR}/${RANDOMPICS} --transition-type grow --transition-fps 60 --transition-duration 1.0 --transition-pos 0.810,0.972 --transition-bezier 0.65,0,0.35,1 --transition-step 255
    wal -i ${DIR}/${RANDOMPICS} --cols16
    pywalfox update
    pywal-discord -t default

    echo "Successfully set a new wallpaper and generated colors from it."
fi

. $HOME/.config/mako/update-colors.sh
. $HOME/.config/spicetify/Themes/Pywal/update-colors.sh