#!/bin/bash

CONFIG_FILES="$HOME/.config/waybar/config.json $HOME/.config/waybar/style.css $HOME/.cache/wal/colors-waybar.css"

trap "killall waybar" EXIT

while true; do
    # Copy colors file
    \cp -f $HOME/.cache/wal/colors-waybar.css $HOME/.config/waybar/
    
    # Kill any existing waybar instances
    killall waybar 2>/dev/null
    sleep 0.2
    
    # Start waybar
    waybar -c $HOME/.config/waybar/config.json -s $HOME/.config/waybar/style.css &
    
    # Wait for file changes
    inotifywait -e create,modify $CONFIG_FILES
    
    # Small delay to avoid rapid restarts
    sleep 0.3
done